[package]
name = "rush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.3"
rustyline = "9.1.2"
shell-words = "1.1.0"

[profile.dev]
incremental = true
